Bootstrap: localimage
From: ubuntu_jammy.sif
%labels
MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>

%setup
    ls -la  ${GITHUB_WORKSPACE} 
     export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache
     rm -f ${SINGULARITY_ROOTFS}/*.txt || true
     bash -c "if [[ -z '${FC}' ]]; then echo 'FC=gfortran ' >> ${SINGULARITY_ROOTFS}/fc.txt ; else echo 'FC is ${FC}'; echo 'FC=${FC} ' >> ${SINGULARITY_ROOTFS}/fc.txt ; fi"
     bash -c "if [[ -z '${USE_SYSV}' ]]; then echo 'USE_SYSV=N ' >> ${SINGULARITY_ROOTFS}/use_sysv.txt ; else echo 'USE_SYSV is ${USE_SYSV}'; echo 'USE_SYSV=${USE_SYSV} ' >> ${SINGULARITY_ROOTFS}/use_sysv.txt ; fi"
     bash -c "if [[ -z '${OMPI}' ]]; then echo 'OMPI=4.1.6 ' >> ${SINGULARITY_ROOTFS}/ompi.txt ; else echo 'OMPI is ${OMPI}'; echo 'OMPI=${OMPI} ' >> ${SINGULARITY_ROOTFS}/ompi.txt ; fi"
     bash -c "if [[ -z '${UCX}' ]]; then echo 'UCX=1.14.1 ' >> ${SINGULARITY_ROOTFS}/ucx.txt ; else echo 'UCX is ${UCX}'; echo 'UCX=${UCX} ' >> ${SINGULARITY_ROOTFS}/ucx.txt ; fi"
     bash -c "if [[ -z '${ARMCI_NETWORK}' ]]; then echo 'ARMCI_NETWORK=MPI-PR ' >> ${SINGULARITY_ROOTFS}/armci_network.txt ; else echo 'ARMCI_NETWORK is ${ARMCI_NETWORK}'; echo 'ARMCI_NETWORK=${ARMCI_NETWORK} ' >> ${SINGULARITY_ROOTFS}/armci_network.txt ; fi"
     bash -c "if [[ -z '${MPI_IMPL}' ]]; then echo 'MPI_IMPL=ompi ' >> ${SINGULARITY_ROOTFS}/mpi_impl.txt ; else echo 'MPI_IMPL is ${MPI_IMPL}'; echo 'MPI_IMPL=${MPI_IMPL} ' >> ${SINGULARITY_ROOTFS}/mpi_impl.txt ; fi"
     bash -c "if [[ -z '${CUDA_CC}' ]]; then echo 'CUDA_CC=90 ' >> ${SINGULARITY_ROOTFS}/cuda_cc.txt ; else echo 'CUDA_CC is ${CUDA_CC}'; echo 'CUDA_CC=${CUDA_CC} ' >> ${SINGULARITY_ROOTFS}/cuda_cc.txt ; fi" 
     bash -c "if [[ -z '${BRANCH}' ]]; then echo 'BRANCH=master ' >> ${SINGULARITY_ROOTFS}/branch.txt ; else echo 'BRANCH is ${BRANCH}'; echo 'BRANCH=${BRANCH} ' >> ${SINGULARITY_ROOTFS}/branch.txt ; fi"
     bash -c "if [[ -z '${MYUSERNAME}' ]]; then echo 'MYUSERNAME=nwchemgit ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; else echo 'MYUSERNAME is ${MYUSERNAME}'; echo 'MYUSERNAME=${MYUSERNAME} ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; fi"
     ls -lrt ${CACHEDIR} || true
     ls -la  ${CACHEDIR}/ || true
     ls -la  ${CACHEDIR}/ompi || true
     ls -la  ${CACHEDIR}/ompi/lib || true
     ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libnwc_simint.a || true
     ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ||true
     bash -c "if [ ! -z "${GITHUB_WORKSPACE}" ]; then mkdir -p ${SINGULARITY_ROOTFS}/nwchem/contrib; rsync -a ${GITHUB_WORKSPACE}/nwchem/src ${SINGULARITY_ROOTFS}/nwchem/. ; rsync -a ${GITHUB_WORKSPACE}/nwchem/contrib/getmem.nwchem ${SINGULARITY_ROOTFS}/nwchem/contrib/. ;rsync -a ${GITHUB_WORKSPACE}/nwchem/travis ${SINGULARITY_ROOTFS}/nwchem/. ; rsync -a ${GITHUB_WORKSPACE}/nwchem/.git ${SINGULARITY_ROOTFS}/nwchem/. ; fi"
     bash -c "if [[  -f ${CACHEDIR}/ompi/lib/libmpi.so ]]; then mkdir -p ${SINGULARITY_ROOTFS}/opt ;rsync -a ${CACHEDIR}/ompi ${SINGULARITY_ROOTFS}/opt/. ; echo ompi/ucx cache fetched ;fi"
     bash -c "if [[  -f ${CACHEDIR}/libext/lib/libnwc_openblas.a ]]; then rsync -a ${CACHEDIR}/libext/* ${SINGULARITY_ROOTFS}/nwchem/src/libext/. ; echo libext cache fetched ;fi"
     bash -c "if [[  -f ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ]]; then rsync -av ${CACHEDIR}/simint.l5_p5_d1.install ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/. ; ln -sf ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint.l5_p5_d1.install  ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint_install;  ls -l ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/; echo simint cache fetched ;fi"

##%files
##    ${GITHUB_WORKSPACE}/nwchem nwchem

%post
#https://sylabs.io/guides/3.6/user-guide/mpi.html
export DEBIAN_FRONTEND=noninteractive 
 export OMPI_DIR=/opt/ompi
 export PATH=$OMPI_DIR/bin:/opt/intel/oneapi/compiler/latest/bin:/opt/intel/oneapi/compiler/latest/linux/bin/intel64:/root//apps/oneapi/compiler/latest/linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
 export LD_LIBRARY_PATH=$OMPI_DIR/lib:/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/lib/x64:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin 
 export LIBRARY_PATH=/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/latest/linux/lib 
 export `cat ./fc.txt`
 export `cat ./use_sysv.txt`
 export `cat ./ompi.txt`
 export `cat ./ucx.txt`
 export `cat ./armci_network.txt`
 export `cat ./mpi_impl.txt`
 export `cat ./cuda_cc.txt` 
 export `cat ./branch.txt`
 export `cat ./myusername.txt`
 echo FC is $FC
 echo OMPI is $OMPI
 echo CUDA_CC $CUDA_CC 
 export ompi_prefix=openmpi-$OMPI
 echo ompi_prefix is $ompi_prefix 
 export ompi_major=$(echo $OMPI | cut -d . -f1) 
 echo ompi_major is $ompi_major 
 export ompi_minor=$(echo $OMPI | cut -d . -f2) 
 echo ompi_minor is $ompi_minor 
 echo ompi_major is $ompi_major 
 if [ $ompi_major = '5' ]; then
    export ompi_options=' --enable-mca-no-build=coll-han '
else
    export ompi_options=' --with-pmi --with-pmi-libdir=/usr/lib/x86_64-linux-gnu --without-verbs '
fi 
 echo ompi_options $ompi_options 
 export UCXVTAG=v$UCX 
 echo standard UCXVTAG is $UCXVTAG 
 if [ $UCX = 1.20.0 ]; then export UCXVTAG=$UCX ; fi 
 echo UCX is $UCX UCXVTAG is $UCXVTAG 
 echo ARMCI_NETWORK is $ARMCI_NETWORK
 echo USE_SYSV is $USE_SYSV 
 echo MPI_IMPL is $MPI_IMPL
 echo BRANCH is $BRANCH
 pwd 
 apt-get -y update 
 apt-get -y install -y tzdata git moreutils curl wget rsync  sudo ca-certificates 
 echo ca_certificate=/etc/ssl/certs/ca-certificates.crt >  ~/.wgetrc 
 echo        "cacert=/etc/ssl/certs/ca-certificates.crt" >> ~/.curlrc 
 if [ $(echo $FC | cut -c -8) = gfortran ]; then
     apt-get -y install -y  ${FC}
 fi
 pwd 
 echo '@@ ls -lart ' 
 ls -lart  
 echo '@@ ls on /opt' 
 ls -lart /opt 
 echo " ==========" 
 pwd 
 echo pwd $(pwd) 
 echo 'ls nwchem' $(ls -lrta nwchem) 
 echo 'ls nwchem/src' $(ls -lrta nwchem/src) 
 if [ ! -f nwchem/src/GNUmakefile ]; then
     git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git
 fi 
 apt-get -y install -y   tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
 g++ gfortran   make ssh patch   unzip perl-base file \
 python3 python3-dev cmake  unzip zip perl automake libtool autoconf flex  \
 libnuma-dev libslurm-dev \
 libnl-3-dev  libnl-route-3-dev udev \
 librdmacm-dev librdmacm1 rdma-core libibverbs-dev  ibverbs-providers  \
 libhwloc-dev libfuse3-dev\
 pkg-config gawk  software-properties-common 
 if [ $ompi_major = '4' ]; then
    apt-get -y install -y libpmi2-0-dev libpmi0-dev
fi 
 apt-get clean 
 echo TTTTT 
 df -h 
 bash -o  pipefail -c  ./nwchem/travis/build_env.sh || true 
 echo TTTTT 
 echo "PATH" $PATH 
 echo "LD_LIBRARY_PATH" $LD_LIBRARY_PATH 
 echo FFFFF 
 echo 'FC -v ' `$FC -v` 
 echo ' CC is ' "$CC" 
 echo ' CXX is ' "$CXX" || true

if [ $CUDA_CC != "cpu" ]; then
export ELPA_NVIDIA=1
export CUDA_VERSION_MAJOR=12 ; export CUDA_VERSION_MINOR=4
 curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg 
  cp cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg 
  echo 'deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /' |  tee /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list 
  curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin 
  mv cuda-*.pin /etc/apt/preferences.d/cuda-repository-pin-600 
  apt-get  update 
 apt-get  -y install cuda-nvcc-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-cudart-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} libcublas-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-nvml-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} 
#figure out CUDA_RUNTIME
export CUDA_ROOT=/usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}
export PATH=${CUDA_ROOT}/bin:$PATH
echo ls cudaroot/bin $(ls -lart ${CUDA_ROOT}/bin)
export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:"$LD_LIBRARY_PATH" 
echo "ls cuda rt available" $(ls ${CUDA_ROOT}/lib64/libcu*) || true
CUDA_RUNTIME=$(nvcc --version |grep Cuda\ compilation | cut -d " " -f 5|sed -e s'/,//')
echo gpu archs available $(nvcc --list-gpu-arch)
echo CUDA_RUNTIME is $CUDA_RUNTIME
#need to add nvcc compiler flags option  -arch=sm_${CUDA_CC}
export NVCC_APPEND_FLAGS=-arch=sm_${CUDA_CC}
echo "looking for libcuda.so" $(find $CUDA_ROOT -name libcuda.so)

 
 dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100 
 apt-get clean
fi

echo check ompi install 
 echo 'ls -l /opt/ompi/lib/libmpi.so' $(ls -l /opt/ompi/lib/libmpi.so) || true 
 if [ ! -f /opt/ompi/lib/libmpi.so ]; then  
     $FC -v 
     wget --progress=dot:giga  https://github.com/openucx/ucx/releases/download/$UCXVTAG/ucx-$UCX.tar.gz -O - | tar xzf - 
     cd ucx-$UCX 
     wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/ucx_malloc.patch 
     wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/ucx1181_malloc.patch 
     if [ $UCX = 1.14.1 ] || [ $UCX = 1.15.0 ]; then
	 patch -p0 < ./ucx_malloc.patch
     else
	 patch -p0 < ./ucx1181_malloc.patch
     fi 
     mkdir build && cd build 
     ../configure --prefix=$OMPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check || { echo "UCX config Failure"; exit 1; }
     make -j4 || { echo "UCX Compilation Failure"; exit 1; }
     make install || { echo "UCX Installation Failure"; exit 1; }
     if [ ! -f $OMPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
     cd ../.. 
     wget  --progress=dot:giga https://download.open-mpi.org/release/open-mpi/v$ompi_major.$ompi_minor/openmpi-$OMPI.tar.gz  -O - | tar xzf -
     cd $ompi_prefix                                                       
     ./configure  --prefix=$OMPI_DIR --with-ucx=$OMPI_DIR --enable-mca-no-build=btl-uct   \
		  $ompi_options \
		  --enable-mpi1-compatibility --with-slurm --without-tm --without-lsf  \
		  --without-sge --without-alps --without-lustre --disable-memchecker \
		  --without-hcoll --disable-static  \
		  --disable-mpi-java --enable-dlopen --without-cuda  \
		  FC=$FC || { echo "OMPI config Failure"; exit 1; }
     head config.log 
     make FC=$FC -j 6  || { echo "OMPI Compilation Failure"; exit 1; }                              
     make install      || { echo "OMPI Installation Failure"; exit 1; }            
     if [ ! -f $OMPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
     echo mpif90 show is $($OMPI_DIR/bin/mpif90 -show) 
     cd .. ; rm -rf *tar*gz openmpi-* ucx-*
 fi 

echo ' check ucx' 
 if [ ! -f $OMPI_DIR//bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
 echo ' /opt/ompi/bin/ucx_info -v ' `/opt/ompi/bin/ucx_info -v|| true` 
 echo ' ucx Transports' `/opt/ompi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` 
 if [ ! -f $OMPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
 echo '********'  
 export PATH=$OMPI_DIR/bin:$PATH
 export LD_LIBRARY_PATH=$OMPI_DIR/lib:$LD_LIBRARY_PATH
 echo ARMCI_NETWORK is $ARMCI_NETWORK
 export NWCHEM_TARGET=LINUX64
 export NWCHEM_MODULES="all python gwmol xtb"
 export USE_OPENMP=1 
 export USE_TBLITE=1 
 if [ "$FC" = "gfortran" ]; then 
   export BUILD_PLUMED=1;    export PYTHON_BIN=python3;   export BUILD_ELPA=1
fi	   
 export USE_LIBXC=1
 export BUILD_OPENBLAS=1
 export BUILD_SCALAPACK=1
 export BLAS_SIZE=8
 export SCALAPACK_SIZE=8
 export USE_MPI=y
 export USE_MPIF=y
 export USE_MPIF4=y
 export USE_HWOPT=n
 export USE_LIBXC=y
 export USE_NOIO=y
 export IPCCSD=y 
 export EACCSD=y 
 export MRCC_METHODS=y 
 export USE_SIMINT=y
 export SIMINT_MAXAM=5
 export PYTHONVERSION=$(python -V| cut -d ' ' -f 2 |cut -d . -f 1-2) 
 ls -l nwchem* || true 
 /usr/bin/env|egrep BUILD_ 
 echo " ==========" 
 pwd 
 echo pwd $(pwd) 
 echo 'ls nwchem' $(ls -lrta nwchem) 
 echo 'ls nwchem/src' $(ls -lrta nwchem/src) 
 bash -o pipefail -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git; fi" 
 cd nwchem 
 echo "output of git describe  --always " `git describe  --always` || true 
 wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/largebasis.patch 
 patch -p1 < largebasis.patch 
 wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/okeep.patch 
 patch -p1 < okeep.patch 
 wget https://github.com/nwchemgit/nwchem/commit/6bd7f90f40faa1d7558787c1134fe6b1b1d22daf.patch -O elpanv.patch 
 patch -p1 < elpanv.patch || true 
 export NWCHEM_TOP=`pwd` 
 echo 'ls -lrta ' $(ls -lrta) 
 echo 'pwd ' $(pwd) 
 cd src 
 echo 'ls -lrta ' $(ls -lrta) 
 echo 'pwd ' $(pwd) 
 ls -lrt libext/lib || true 
 make nwchem_config || { echo "config Failure"; exit 1; } 
 if [ $USE_SYSV = 'Y' ]; then
    export M_S='ARMCI_DEFAULT_SHMMAX_UBOUND=131072 --enable-sysv '
else
    export M_S='ARMCI_DEFAULT_SHMMAX_UBOUND=131072 '
fi 
 echo M_S is $M_S 
echo 'ls ~/' `ls -lrt ~/` 
 echo '222 PATH is ' `/usr/bin/env | grep PATH` 
 echo '111 which FC ' `which $FC` || true 
 mpif90 -show 
 echo FC is $FC 
 $FC -v 
 echo MAYBE_SYSVSHMEM is $M_S 
 make MAYBE_SYSVSHMEM=$M_S FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
 FC=$FC ../contrib/getmem.nwchem 2000   
 make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }
 grep SYSV tools/build/comex/config.log 
 ldd  ../bin/LINUX64/nwchem  
if [ -f /opt/intel/oneapi/compiler/latest/env/vars.sh ]; then  
    rsync -av /opt/intel/oneapi/compiler/latest/lib/lib*.so* $OMPI_DIR/lib/.
fi 
  rm -rf /opt/intel/oneapi/  /opt/nwchem/src/tce /opt/nwchem/src/NWints/simint/libsimint_source/simint.l?_p?_d? || true 
 DEBIAN_FRONTEND=noninteractive apt-get clean -y 
 DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge 
 echo MANDELETE >  /etc/locale.nopurge 
 echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge 
 echo en_US.UTF-8 >> /etc/locale.nopurge 
 localepurge 
 rm -rf /usr/share/doc  /usr/share/man 
 du -sh /opt/nwchem 
 du -sk /opt/nwchem/*|sort -n 
 rm -rf ../.git 
 rm -rf tce tools nwdft NWints/simint/libsimint_source/simint.l?_p?_d? geom symmetry util nwxc ddscf lapack blas rism argos peigs rmdft gradients symmetry property smd lucia dplot propery hessian ccsd mp2_grad moints cafe analyz dimqm   develop libext/scalapack libext/openblas libext/libxc/libxc* libext/plumed* libext/libext_utils  libext/elpa  ../lib 
 du -sh * |sort -n 
 cd ../.. 
 du -sh nwchem 
 du -sk *|sort -n  
if [ $FC = "ifx" ] || [ $FC  = "ifort" ]; then 
    rm -rf ~/apps  /var/intel  l_*sh
fi
 ls -lrth    
  ldd  /opt/nwchem/bin/nwchem  
 du -sk *|sort -n 
 echo "dddddddddddd"  
 dpkg-query -Wf '${Installed-Size}t${Package}\n' | sort -n | tail -n 100 
 echo "dddddddddddd" 
  du -sk /tmp/* || true 
  ls -lart /tmp ||true 
  apt-get  -y purge cmake git  gcc-11  g++-11  gfortran-11  libstdc++-11-dev  libgcc-11-dev git 
 apt-get -y install libgcc-s1 libgfortran5 
 apt-get -y autoremove && apt-get clean
rm -rf /var/lib/apt/lists/*




#clean unnecessary packages

#apt-get -y purge curl wget tar  cmake  unzip zip perl automake libtool autoconf flex  \
#&&  apt-get -y autoremove && apt-get clean

#cd /data
%environment
export OMPI_DIR=/opt/ompi
export OMP_NUM_THREADS=1
export SINGULARITY_OMP_NUM_THREADS=1
export COMEX_MAX_NB_OUTSTANDING=12
#export nwchem_hash=77ba3a6e1dd6f9ba26879d0416bb93b302f1f4f7
#export NWCHEM_TOP=/opt/nwchem
export NWCHEM_SHARE=/opt/nwchem/share/
export FFIELD=amber
export AMBER_1=$NWCHEM_SHARE/data/amber_s/
export AMBER_2=$NWCHEM_SHARE/data/amber_q/
export AMBER_3=$NWCHEM_SHARE/data/amber_x/
export AMBER_4=$NWCHEM_SHARE/data/amber_u/
export SPCE=${NWCHEM_SHARE}/data/solvents/spce.rst
export CHARMM_S=$NWCHEM_SHARE/data/charmm_s/
export CHARMM_X=$NWCHEM_SHARE/data/charmm_x/
export PATH=$PATH:/opt/nwchem/bin/
export PATH=$OMPI_DIR/bin:$PATH
export NWCHEM_BASIS_LIBRARY=${NWCHEM_SHARE}//libraries/
export NWCHEM_NWPW_LIBRARY=${NWCHEM_SHARE}//libraryps/
export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:"$LD_LIBRARY_PATH" 
export LD_LIBRARY_PATH=$OMPI_DIR/lib:$LD_LIBRARY_PATH
#%runscript
#exec /bin/bash "$@"
