Bootstrap: localimage
From: ubuntu_noble.sif
%labels
MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>

%setup
    set -ex
    env
    ls -la  ${GITHUB_WORKSPACE} 
     export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache
     rm -f ${SINGULARITY_ROOTFS}/*.txt || true
     bash -c "if [[ -z '${FC}' ]]; then echo 'FC=gfortran ' >> ${SINGULARITY_ROOTFS}/fc.txt ; else echo 'FC is ${FC}'; echo 'FC=${FC} ' >> ${SINGULARITY_ROOTFS}/fc.txt ; fi"
     bash -c "if [[ -z '${USE_SYSV}' ]]; then echo 'USE_SYSV=N ' >> ${SINGULARITY_ROOTFS}/use_sysv.txt ; else echo 'USE_SYSV is ${USE_SYSV}'; echo 'USE_SYSV=${USE_SYSV} ' >> ${SINGULARITY_ROOTFS}/use_sysv.txt ; fi"
     bash -c "if [[ -z '${MPICH}' ]]; then echo 'MPICH=3.4.2 ' >> ${SINGULARITY_ROOTFS}/mpich.txt ; else echo 'MPICH is ${MPICH}'; echo 'MPICH=${MPICH} ' >> ${SINGULARITY_ROOTFS}/mpich.txt ; fi"
     bash -c "if [[ -z '${OMPI}' ]]; then echo 'OMPI=4.1.6 ' >> ${SINGULARITY_ROOTFS}/ompi.txt ; else echo 'OMPI is ${OMPI}'; echo 'OMPI=${OMPI} ' >> ${SINGULARITY_ROOTFS}/ompi.txt ; fi"
     echo UCX is ${UCX}
     bash -c "if [[  -z ${UCX} ]]; then  echo echo 'UCX=1.14.1'  >> ${SINGULARITY_ROOTFS}/ucx.txt; else echo 'UCX=${UCX} ' >> ${SINGULARITY_ROOTFS}/ucx.txt ; fi"
     cat ${SINGULARITY_ROOTFS}/ucx.txt
     echo OFI is ${OFI}
     bash -c "if [[  -z ${OFI} ]]; then  echo 'OFI=1.19.0' >> ${SINGULARITY_ROOTFS}/ofi.txt; else echo 'OFI=${OFI} ' >> ${SINGULARITY_ROOTFS}/ofi.txt ; fi"
     cat ${SINGULARITY_ROOTFS}/ofi.txt
     bash -c "if [[  -z ${PMIX} ]]; then  echo 'PMIX=N' >> ${SINGULARITY_ROOTFS}/pmix.txt; else echo 'PMIX=${PMIX} ' >> ${SINGULARITY_ROOTFS}/pmix.txt ; fi"
     cat ${SINGULARITY_ROOTFS}/pmix.txt
     ls -lrt ${SINGULARITY_ROOTFS}/*txt
     bash -c "if [[ -z '${MPICH_DEVICE}' ]]; then echo 'MPICH_DEVICE=ch4:ofi '  >> ${SINGULARITY_ROOTFS}/mpich_device.txt; else echo 'MPICH_DEVICE=${MPICH_DEVICE} ' >> ${SINGULARITY_ROOTFS}/mpich_device.txt ; fi"
     bash -c "if [[ -z '${ARMCI_NETWORK}' ]]; then echo 'ARMCI_NETWORK=MPI-PR ' >> ${SINGULARITY_ROOTFS}/armci_network.txt ; else echo 'ARMCI_NETWORK is ${ARMCI_NETWORK}'; echo 'ARMCI_NETWORK=${ARMCI_NETWORK} ' >> ${SINGULARITY_ROOTFS}/armci_network.txt ; fi"
     bash -c "if [[ -z '${MPI_IMPL}' ]]; then echo 'MPI_IMPL=ompi '>> ${SINGULARITY_ROOTFS}/mpi_impl.txt; else echo 'MPI_IMPL=${MPI_IMPL} ' >> ${SINGULARITY_ROOTFS}/mpi_impl.txt ; fi"
     bash -c "if [[ -z '${CUDA_CC}' ]]; then echo 'CUDA_CC=cpu ' >> ${SINGULARITY_ROOTFS}/cuda_cc.txt ; else echo 'CUDA_CC is ${CUDA_CC}'; echo 'CUDA_CC=${CUDA_CC} ' >> ${SINGULARITY_ROOTFS}/cuda_cc.txt ; fi" 
     bash -c "if [[ -z '${BRANCH}' ]]; then echo 'BRANCH=master ' >> ${SINGULARITY_ROOTFS}/branch.txt ; else echo 'BRANCH is ${BRANCH}'; echo 'BRANCH=${BRANCH} ' >> ${SINGULARITY_ROOTFS}/branch.txt ; fi"
     bash -c "if [[ -z '${MYUSERNAME}' ]]; then echo 'MYUSERNAME=nwchemgit ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; else echo 'MYUSERNAME is ${MYUSERNAME}'; echo 'MYUSERNAME=${MYUSERNAME} ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; fi"
     ls -lrt ${SINGULARITY_ROOTFS}/*txt
     ls -lrt ${CACHEDIR} || true
     ls -la  ${CACHEDIR}/ || true
     ls -la  ${CACHEDIR}/mpi || true
     ls -la  ${CACHEDIR}/mpi/lib || true
     ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libnwc_simint.a || true
     ls -la  ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ||true
     bash -c "if [ ! -z "${GITHUB_WORKSPACE}" ]; then mkdir -p ${SINGULARITY_ROOTFS}/nwchem/contrib; rsync -a ${GITHUB_WORKSPACE}/nwchem/src ${SINGULARITY_ROOTFS}/nwchem/. ; rsync -a ${GITHUB_WORKSPACE}/nwchem/contrib/getmem.nwchem ${SINGULARITY_ROOTFS}/nwchem/contrib/. ;rsync -a ${GITHUB_WORKSPACE}/nwchem/travis ${SINGULARITY_ROOTFS}/nwchem/. ; rsync -a ${GITHUB_WORKSPACE}/nwchem/.git ${SINGULARITY_ROOTFS}/nwchem/. ; fi"
     bash -c "if [[  -f ${CACHEDIR}/mpi/lib/libmpi.so ]]; then mkdir -p ${SINGULARITY_ROOTFS}/opt ;rsync -a ${CACHEDIR}/mpi ${SINGULARITY_ROOTFS}/opt/. ; echo ompi/ucx cache fetched ;fi"
     bash -c "if [[  -f ${CACHEDIR}/libext/lib/libnwc_openblas.a ]]; then rsync -a ${CACHEDIR}/libext/* ${SINGULARITY_ROOTFS}/nwchem/src/libext/. ; echo libext cache fetched ;fi"
     bash -c "if [[  -f ${CACHEDIR}/simint.l5_p5_d1.install/lib/libsimint.a ]]; then rsync -av ${CACHEDIR}/simint.l5_p5_d1.install ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/. ; ln -sf ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint.l5_p5_d1.install  ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/simint_install;  ls -l ${SINGULARITY_ROOTFS}/nwchem/src/NWints/simint/libsimint_source/; echo simint cache fetched ;fi"
     set +ex
##%files
##    ${GITHUB_WORKSPACE}/nwchem nwchem

%post
set -ex
 export MPICH_AURORA="4.3.0" 
# export PMIX="4.2.9" 
 export `cat ./fc.txt`
 export `cat ./use_sysv.txt`
 if [ ! -f ./mpi_impl.txt ]; then
     echo MPI_IMPL not defined
     exit 1
 else
     export `cat ./mpi_impl.txt`
     echo MPI_IMPL is $MPI_IMPL
 fi
 if [ $MPI_IMPL = "ompi" ]; then
     if [ ! -f ./ompi.txt ]; then
	 echo OMPI not defined
	 exit 1
     else
	 export `cat ./ompi.txt`
	 echo OMPI is $OMPI
     fi
     export OMPI_DIR=/opt/mpi
     export MPI_DIR=/opt/mpi
     export ompi_prefix=openmpi-$OMPI
     echo ompi_prefix is $ompi_prefix 
     export ompi_major=$(echo $OMPI | cut -d . -f1) 
     echo ompi_major is $ompi_major 
     export ompi_minor=$(echo $OMPI | cut -d . -f2) 
     echo ompi_minor is $ompi_minor 
     echo ompi_major is $ompi_major 
     if [ $ompi_major = '5' ]; then
	 export ompi_options=' --enable-mca-no-build=coll-han '
     else
	 export ompi_options=' --with-pmi --with-pmi-libdir=/usr/lib/x86_64-linux-gnu --without-verbs '
     fi 
     echo ompi_options $ompi_options 
     mpich_major=-1
     mpich_minor=-1
 fi
 if [ $MPI_IMPL = "mpich" ]; then
     if [ ! -f ./mpich.txt ]; then
	 ls -lrt *txt
	 echo MPICH not defined
	 exit 1
     else
	 export `cat ./mpich.txt`
	 echo MPICH is $MPICH
     fi
     export MPICH_DIR=/opt/mpi
     export MPI_DIR=/opt/mpi

     if [ $MPICH = aurora ]; then
	 export MPICH_VERSION=$MPICH_AURORA
     else
	 export MPICH_VERSION=$MPICH
     fi
     if [ ! -f ./mpich_device.txt ]; then
	 echo MPICH_DEVICE not defined
	 exit 1
     else
	 export `cat ./mpich_device.txt`
	 echo MPICH_DEVICE is $MPICH_DEVICE
     fi
     export mpich_prefix=mpich-$MPICH_VERSION
     echo mpich_prefix is $mpich_prefix 
     export mpich_major=$(echo $MPICH_VERSION | cut -d . -f1) 
     echo mpich_major is $mpich_major 
     export mpich_minor=$(echo $MPICH_VERSION | cut -d . -f2) 
     echo mpich_minor is $mpich_minor 
     echo mpich_major is $mpich_major 
     if [ $mpich_major = '4' ]; then
	 export mpich_options=' '
     else
	 export mpich_options=' '
     fi 
     if [ $MPICH = aurora ]; then
	 export mpich_options=$mpich_options' --disable-maintainer-mode --with-pm=no --enable-romio --with-slurm=no --with-pmi=pmix --with-pmix=/opt/mpi '
     fi
     echo mpich_options are $mpich_options
     ompi_major=-1
     ompi_minor=-1
 fi
 if [  -f ./ucx.txt ]; then
     echo cat ucx `cat ./ucx.txt`
     export `cat ./ucx.txt`
     echo UCX is $UCX
     if [ $UCX != "N" ]; then
	 export UCXVTAG=v$UCX 
	 echo standard UCXVTAG is $UCXVTAG 
#	 if [ $UCX = 1.20.0 ]; then export UCXVTAG=$UCX ; fi
	 echo UCX is $UCX UCXVTAG is $UCXVTAG
         export ucx_or_ofi="--enable-mca-no-build=btl-uct --with-ucx="${MPI_DIR}
     fi
 fi
 if [  -f ./ofi.txt ]; then
      export `cat ./ofi.txt`
      echo OFI is $OFI
      if [ $OFI != "N" ]; then
	  export ucx_or_ofi="--with-ofi="${MPI_DIR}
      fi
 fi
 if [ $UCX = "N" ] &&  [ $OFI = "N" ]; then
     echo neither UCX nor OFI defined
     echo exiting
     exit 1
 fi
 if [ $UCX != "N" ] &&  [ $OFI != "N" ]; then
     echo both UCX and OFI are set
     echo exiting
     exit 1
 fi
 if [  -f ./pmix.txt ]; then
      export `cat ./pmix.txt`
      echo PMIX is $PMIX
      if [ $PMIX != "N" ]; then
	  if [ $MPI_IMPL = "mpich" ]; then
	      export pmix_options="--with-pmi=pmix"
	  fi
	  export pmix_options="${pmix_options} --with-pmix=${MPI_DIR}"
      fi
 fi
echo ucx_or_ofi is $ucx_or_ofi
 export `cat ./armci_network.txt`
 export `cat ./cuda_cc.txt` 
 export `cat ./branch.txt`
 export `cat ./myusername.txt`
 echo FC is $FC
 echo CUDA_CC $CUDA_CC 
 echo ARMCI_NETWORK is $ARMCI_NETWORK
 echo USE_SYSV is $USE_SYSV 
 echo MPI_IMPL is $MPI_IMPL
 echo BRANCH is $BRANCH
export DEBIAN_FRONTEND=noninteractive 
export PATH=$MPI_DIR/bin:/opt/intel/oneapi/compiler/latest/bin:/opt/intel/oneapi/compiler/latest/linux/bin/intel64:/root//apps/oneapi/compiler/latest/linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
 export LD_LIBRARY_PATH=$MPI_DIR/lib:/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/lib/x64:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin 
 export LIBRARY_PATH=/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/latest/linux/lib 
 pwd 
 apt-get -y update 
 apt-get -y install -y tzdata git moreutils curl wget rsync  sudo ca-certificates 
 echo ca_certificate=/etc/ssl/certs/ca-certificates.crt >  ~/.wgetrc 
 echo        "cacert=/etc/ssl/certs/ca-certificates.crt" >> ~/.curlrc 
 if [ $(echo $FC | cut -c -8) = gfortran ]; then
     apt-get -y install -y  ${FC}
 fi
 pwd 
 echo '@@ ls -lart ' 
 ls -lart  
 echo '@@ ls on /opt' 
 ls -lart /opt 
 echo " ==========" 
 pwd 
 apt-get -y install -y   tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
 g++ gfortran   make ssh patch   unzip perl-base file \
 python3 python3-dev python-is-python3 cmake  unzip zip perl automake libtool autoconf flex  \
 libnuma-dev libslurm-dev \
 libnl-3-dev  libnl-route-3-dev udev \
 librdmacm-dev librdmacm1 rdma-core libibverbs-dev  ibverbs-providers  \
 libhwloc-dev libfuse3-dev\
 libconfig-dev libsensors-dev libuv1-dev libfuse-dev libyaml-dev libjson-c-dev libcurl4-openssl-dev  \
 libevdev-dev libevent-dev lmod \
 pkg-config gawk  software-properties-common 
 if [ $ompi_major = '4' ] || [ $mpich_major = '3' ] || [ $mpich_major = '4' ]; then
    apt-get -y install -y libpmi2-0-dev libpmi0-dev
fi 
 if [ $mpich_major = '5' ] || [ $ompi_major = '5' ]; then
    apt-get -y install -y libpmix-bin libpmix-dev libpmix2
fi 
 export GCC_VERSION=11 
 add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt-get update 
 apt-get install -q=2 -y  gcc-"$GCC_VERSION"  g++-"$GCC_VERSION" gfortran-"$GCC_VERSION" libgfortran-"$GCC_VERSION"-dev bzip2 gnupg2
 update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-"$GCC_VERSION" 100
 update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-"$GCC_VERSION" 100
 update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-"$GCC_VERSION" 100
 apt-get clean
 echo TTTTT
 df -h
 bash -o  pipefail -c  ./nwchem/travis/build_env.sh || true
 echo TTTTT
 echo "PATH" $PATH
 echo "LD_LIBRARY_PATH" $LD_LIBRARY_PATH 
 echo FFFFF 
 echo 'FC -v ' `$FC -v` 
 echo ' CC is ' "$CC" 
 echo ' CXX is ' "$CXX" || true

if [ $CUDA_CC != "cpu" ]; then
export ELPA_NVIDIA=1
export CUDA_VERSION_MAJOR=12 ; export CUDA_VERSION_MINOR=6
 curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-archive-keyring.gpg
  cp cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg
  echo 'deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/ /' |  tee /etc/apt/sources.list.d/cuda-ubuntu2404-x86_64.list
  curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
  mv cuda-*.pin /etc/apt/preferences.d/cuda-repository-pin-600
  apt-get  update
  apt-get  -y install cuda-nvcc-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-cudart-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} libcublas-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-nvml-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} \
 libnccl-dev
#figure out CUDA_RUNTIME
export CUDA_ROOT=/usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}
export PATH=${CUDA_ROOT}/bin:$PATH
echo ls cudaroot/bin $(ls -lart ${CUDA_ROOT}/bin)
export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:"$LD_LIBRARY_PATH" 
echo "ls cuda rt available" $(ls ${CUDA_ROOT}/lib64/libcu*) || true
CUDA_RUNTIME=$(nvcc --version |grep Cuda\ compilation | cut -d " " -f 5|sed -e s'/,//')
echo gpu archs available $(nvcc --list-gpu-arch)
echo CUDA_RUNTIME is $CUDA_RUNTIME
#need to add nvcc compiler flags option  -arch=sm_${CUDA_CC}
export NVCC_APPEND_FLAGS=-arch=sm_${CUDA_CC}
echo "looking for libcuda.so" $(find $CUDA_ROOT -name libcuda.so)
 dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100 
 apt-get clean
fi
     
export ORGPWD=$(pwd)
echo ORGPWD is $ORGPWD
if [ $UCX != "N" ]; then
    echo check ucx install 
    echo 'ls -l /opt/mpi/lib/libuct.so' $(ls -l /opt/mpi/lib/libuct.so) || true 
    if [ ! -f /opt/mpi/lib/libuct.so ]; then  
	$FC -v 
	wget --progress=dot:giga  https://github.com/openucx/ucx/releases/download/$UCXVTAG/ucx-$UCX.tar.gz -O - | tar xzf - 
	cd ucx-$UCX 
	wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/ucx_malloc.patch 
	wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/ucx1181_malloc.patch 
	if [ $UCX = 1.14.1 ] || [ $UCX = 1.15.0 ]; then
	    patch -p0 < ./ucx_malloc.patch
	else
	    patch -p0 < ./ucx1181_malloc.patch
	fi 
	mkdir build && cd build 
	../configure --prefix=$MPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check || { echo "UCX config Failure"; exit 1; }
	make -j4 || { echo "UCX Compilation Failure"; exit 1; }
	make install || { echo "UCX Installation Failure"; exit 1; }
	if [ ! -f $MPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
	cd $ORGPWD
    else
	echo "using UCX cached installtation"
    fi
    echo ' check ucx' 
    if [ ! -f $MPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
    echo ' /opt/mpi/bin/ucx_info -v ' `/opt/mpi/bin/ucx_info -v|| true` 
    echo ' ucx Transports' `/opt/mpi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` 
fi
if [ $OFI != "N" ]; then
    #install cxi
    echo 'ls -l /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec' $(ls -l /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec) || true 
    if [ ! -f /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec ]; then  
	cd / ; ls -lrta  
	mkdir -p $MPI_DIR  
	cd $MPI_DIR
	export SHSTAG=release/shs-12.0.2
	wget --progress=dot:giga https://github.com/HewlettPackard/shs-cassini-headers/archive/refs/heads/main.tar.gz -O - | tar xzf -
	mv shs-cassini-headers* shs-cassini-headers
#	git clone --branch $SHSTAG https://github.com/HewlettPackard/shs-cxi-driver
	wget https://github.com/HewlettPackard/shs-cxi-driver/archive/refs/tags/${SHSTAG}.tar.gz -O - |tar xzf -
	mv shs-cxi-driver* shs-cxi-driver
	cd $ORGPWD
	wget --progress=dot:giga https://github.com/HewlettPackard/shs-libcxi/archive/refs/tags/${SHSTAG}.tar.gz -O - | tar xzf -
	mv shs-libcxi-* shs-libcxi
	cd shs-libcxi 
	sh autogen.sh 
	./configure --prefix=$MPI_DIR 
	make CFLAGS=-I$MPI_DIR/shs-cassini-headers/include/\ -I$MPI_DIR/shs-cxi-driver/include/ pkg_CFLAGS=-Wall -i 
	make CFLAGS=-I$MPI_DIR/shs-cassini-headers/include/\ -I$MPI_DIR/shs-cxi-driver/include/ install-dist_cxi_yamlDATA install-man install-pkgconfigDATA install-pkgincludeHEADERS  install-exec   
	export libfabric_options=--enable-cxi=$MPI_DIR\ --with-cassini-headers=$MPI_DIR/shs-cassini-headers\ --with-cxi-uapi-headers=$MPI_DIR/shs-cxi-driver
	echo 'libfabric_options are' $libfabric_options
	rm -rf shs-*
    fi
    cd  $ORGPWD
    #install OFI
    echo 'ls -l /opt/mpi/lib/libfabrics.so' $(ls -l /opt/mpi/lib/libfabrics.so) || true 
    if [ ! -f /opt/mpi/lib/libfabrics.so ]; then  
	if [ ${OFI} = builtin ]; then
	    echo 'using builtin OFI - nothing to download'
	else
	    if [ ${OFI} = git ]; then
		export COMMIT=c3420a7402a10f5fe3f475ac5eb39b3f2837f8d1
		wget  --progress=dot:giga https://github.com/ofiwg/libfabric/archive/$COMMIT.tar.gz -O - | tar --no-same-owner xzf -
		ls -lrt 
		mv libfabric-$COMMIT libfabric-git 
		cd libfabric-git && sh autogen.sh;
		apt-get install -y libconfig-dev libsensors-dev libuv1-dev libfuse-dev libyaml-dev libjson-c-dev libcurl4-openssl-dev  
	    else
		wget --progress=dot:giga  https://github.com/ofiwg/libfabric/releases/download/v$OFI/libfabric-$OFI.tar.bz2 -O - | tar --no-same-owner  -xjf -
		#	    export libfabric_options=' '
	    fi 
	    cd  $ORGPWD ; echo 'pwd ' $(pwd) ;ls -lrta 
	    cd libfabric-${OFI}
	    mkdir build && cd build 
	    ../configure --prefix=$MPI_DIR $libfabric_options || { echo "OFI configuration Failure"; exit 1; }
	    make -j4 || { echo "OFI Compilation Failure"; exit 1; }
	    make install || { echo "OFI Installation Failure"; exit 1; }
	    if [ ! -f $MPI_DIR/bin/fi_info ]; then echo fi_info\ not\ found ; exit 1 ; fi 
	fi 
	cd .. 
	rm -rf libfabr* 
    fi
fi
echo ucx_or_ofi is $ucx_or_ofi
cd $ORGPWD
if [ $PMIX != "N" ]; then
    if [ ! -f /opt/mpi/lib/libpmix.so ]; then
	wget https://github.com/openpmix/openpmix/releases/download/v${PMIX}/pmix-${PMIX}.tar.gz 
	tar xzf pmix-${PMIX}.tar.gz 
	cd pmix-${PMIX} 
	./configure --prefix=${MPI_DIR} || { echo "PMIX configuration Failure"; exit 1; }
	make -j3 || { echo "PMIX Compilation Failure"; exit 1; }
	make -j3 install || { echo "PMIX installation Failure"; exit 1; }
	cd .. 
	rm -rf pmix-*.*
    fi
fi
#installing xpmem
echo 'ls -l /opt/mpi/lib/libxpmem.so' $(ls -l /opt/mpi/lib/libxpmem.so) || true
if [ ! -f /opt/mpi/lib/libxpmem.so ]; then
    wget --progress=dot:giga https://github.com/Cray-HPE/xpmem/tarball/master -O xpmem.tar.gz 
    tar xzf xpmem.tar.gz 
    rm xpmem.tar.gz 
    cd Cray-HPE-xpmem* 
    sh autogen.sh 
    ./configure --prefix=$MPI_DIR --disable-kernel-module  || { echo "XPMEM Configuration Failure"; exit 1; }
    make -j3 || { echo "XPMEM Compilation Failure"; exit 1; }
    make install || { echo "XPMEM Installation Failure"; exit 1; }
fi
cd $ORGPWD
if [ -n "${OMPI+1}" ]; then
    echo check ompi install 
    echo 'ls -l /opt/mpi/lib/libmpi.so' $(ls -l /opt/mpi/lib/libmpi.so) || true 
    if [ ! -f /opt/mpi/lib/libmpi.so ]; then
	wget  --progress=dot:giga https://download.open-mpi.org/release/open-mpi/v$ompi_major.$ompi_minor/openmpi-$OMPI.tar.gz  -O - | tar xzf -
	cd $ompi_prefix                                                       
	./configure  --prefix=${MPI_DIR} \
	$ucx_or_ofi   \
		     $ompi_options \
		     --with-xpmem=$MPI_DIR \
		     $pmix_otions \
		     --enable-mpi1-compatibility --with-slurm --without-tm --without-lsf  \
		     --without-sge --without-lustre --disable-memchecker \
		     --without-hcoll --disable-static  \
		     --disable-mpi-java --enable-dlopen --without-cuda  \
		     FC=$FC || { echo "OMPI config Failure"; exit 1; }
	head config.log 
	make FC=$FC -j 6  || { echo "OMPI Compilation Failure"; exit 1; }
	make install      || { echo "OMPI Installation Failure"; exit 1; }
	if [ ! -f $MPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
	echo mpif90 show is $($MPI_DIR/bin/mpif90 -show) 
	cd .. ; rm -rf *tar*gz openmpi-* ucx-*
    else
	echo using cached OMPI installation
    fi
fi

if [ -n "${MPICH+1}" ]; then
    echo check mpich install 
    echo 'ls -l /opt/mpi/lib/libmpich.so' $(ls -l /opt/mpi/lib/libmpich.so) || true 
    if [ ! -f /opt/mpi/lib/libmpich.so ]; then
	$FC -v
#	if [ $MPICH = aurora ]; then
#	fi 
	if [ $mpich_major = '4' ] || [ $mpich_major = '5' ]; then
	 export mpich_options="$mpich_options $pmix_options"
	fi
	echo ' mpich_options is set to' $mpich_options 
	wget  --progress=dot:giga https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz  -O - | tar xzf -   
	cd $mpich_prefix
	if [ $mpich_major = '3' ]; then
	    wget https://raw.githubusercontent.com/pmodels/mpich/refs/tags/v4.3.2/src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c 
	    mv slurm_query_node_list.c src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
	fi 
	./configure  --prefix=$MPI_DIR   \
	$ucx_or_ofi   \
	$mpich_options \
	    --with-device=$MPICH_DEVICE  \
	    --enable-fortran=all \
	    --disable-opencl --enable-silent-rules \
	    --disable-cuda \
	    --with-xpmem=$MPI_DIR \
	    FFLAGS=' -fallow-argument-mismatch ' \
	    FCFLAGS=' -fallow-argument-mismatch ' \
	    FC=$FC || { echo "MPICH Configuration Failure"; exit 1; }
	head config.log 
	tail -300 config.log
	make FC=$FC -j 6 || { echo "MPICH Compilation Failure"; exit 1; }    
	make install|| { echo "MPICH Installation Failure"; exit 1; }
	cd .. ; rm -rf *tar*gz mpich*
    else
	echo using cached MPICH installation
    fi
fi
cd $ORGPWD

 if [ ! -f $MPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
 echo '********'  
 export PATH=$MPI_DIR/bin:$PATH
 export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
 echo ARMCI_NETWORK is $ARMCI_NETWORK
 export NWCHEM_TARGET=LINUX64
 export NWCHEM_MODULES="all python gwmol xtb"
 export USE_OPENMP=1 
 export USE_TBLITE=1 
 if [ "$FC" = "gfortran" ]; then 
   export BUILD_PLUMED=1;    export PYTHON_BIN=python3;   export BUILD_ELPA=1
fi	   
 export USE_LIBXC=1
 export BUILD_OPENBLAS=1
 export BUILD_SCALAPACK=1
 export BLAS_SIZE=8
 export SCALAPACK_SIZE=8
 export USE_MPI=y
 export USE_MPIF=y
 export USE_MPIF4=y
 export USE_HWOPT=n
 export USE_LIBXC=y
 export USE_NOIO=y
 export IPCCSD=y 
 export EACCSD=y 
 export MRCC_METHODS=y 
 export USE_SIMINT=y
 export SIMINT_MAXAM=5
 export PYTHONVERSION=$(python -V| cut -d ' ' -f 2 |cut -d . -f 1-2) 
 /usr/bin/env|egrep BUILD_ 
 echo " ==========" 
 pwd 
 echo pwd $(pwd) 
 echo 'ls nwchem' $(ls -lrta nwchem) 
 echo 'ls nwchem/src' $(ls -lrta nwchem/src) 
 bash -o pipefail -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git; fi" 
 cd nwchem 
 echo "output of git describe  --always " `git describe  --always` || true 
 wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/largebasis.patch 
 patch -p1 < largebasis.patch 
 wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/okeep.patch 
 patch -p1 < okeep.patch 
 wget https://github.com/nwchemgit/nwchem/commit/6bd7f90f40faa1d7558787c1134fe6b1b1d22daf.patch -O elpanv.patch 
 patch -p1 < elpanv.patch || true 
 export NWCHEM_TOP=`pwd` 
 echo 'ls -lrta ' $(ls -lrta) 
 echo 'pwd ' $(pwd) 
 cd src 
 echo 'ls -lrta ' $(ls -lrta) 
 echo 'pwd ' $(pwd) 
 ls -lrt libext/lib || true 
 make nwchem_config || { echo "config Failure"; exit 1; } 
 if [ $USE_SYSV = 'Y' ]; then
    export M_S='ARMCI_DEFAULT_SHMMAX_UBOUND=131072 --enable-sysv '
else
    export M_S='ARMCI_DEFAULT_SHMMAX_UBOUND=131072 '
fi 
 echo M_S is $M_S 
echo 'ls ~/' `ls -lrt ~/` 
 echo '222 PATH is ' `/usr/bin/env | grep PATH` 
 echo '111 which FC ' `which $FC` || true 
 mpif90 -show 
 echo FC is $FC 
 $FC -v 
 echo MAYBE_SYSVSHMEM is $M_S 
 make MAYBE_SYSVSHMEM=$M_S FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
 FC=$FC ../contrib/getmem.nwchem 2000   
 make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }
 grep SYSV tools/build/comex/config.log 
 ldd  ../bin/LINUX64/nwchem  
if [ -f /opt/intel/oneapi/compiler/latest/env/vars.sh ]; then  
    rsync -av /opt/intel/oneapi/compiler/latest/lib/lib*.so* $MPI_DIR/lib/.
fi 
  rm -rf /opt/intel/oneapi/  /opt/nwchem/src/tce /opt/nwchem/src/NWints/simint/libsimint_source/simint.l?_p?_d? || true 
 DEBIAN_FRONTEND=noninteractive apt-get clean -y 
 DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge 
 echo MANDELETE >  /etc/locale.nopurge 
 echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge 
 echo en_US.UTF-8 >> /etc/locale.nopurge 
 localepurge 
 rm -rf /usr/share/doc  /usr/share/man 
 du -sh /opt/nwchem 
 du -sk /opt/nwchem/*|sort -n 
 rm -rf ../.git 
 rm -rf tce tools nwdft NWints/simint/libsimint_source/simint.l?_p?_d? geom symmetry util nwxc ddscf lapack blas rism argos peigs rmdft gradients symmetry property smd lucia dplot propery hessian ccsd mp2_grad moints cafe analyz dimqm   develop libext/scalapack libext/openblas libext/libxc/libxc* libext/plumed* libext/libext_utils  libext/elpa  ../lib 
 du -sh * |sort -n 
 cd ../.. 
 du -sh nwchem 
 du -sk *|sort -n  
if [ $FC = "ifx" ] || [ $FC  = "ifort" ]; then 
    rm -rf ~/apps  /var/intel  l_*sh
fi
 ls -lrth    
  ldd  /opt/nwchem/bin/nwchem  
 du -sk *|sort -n 
 echo "dddddddddddd"  
 dpkg-query -Wf '${Installed-Size}t${Package}\n' | sort -n | tail -n 100 
 echo "dddddddddddd" 
  du -sk /tmp/* || true 
  ls -lart /tmp ||true 
  apt-get  -y purge cmake git  gcc-11  g++-11  gfortran-11  libstdc++-11-dev  libgcc-11-dev git 
 apt-get -y install libgcc-s1 libgfortran5 
 apt-get -y autoremove && apt-get clean
rm -rf /var/lib/apt/lists/*




#clean unnecessary packages

#apt-get -y purge curl wget tar  cmake  unzip zip perl automake libtool autoconf flex  \
#&&  apt-get -y autoremove && apt-get clean

#cd /data
%environment
export MPI_DIR=/opt/mpi
export OMP_NUM_THREADS=1
export SINGULARITY_OMP_NUM_THREADS=1
export COMEX_MAX_NB_OUTSTANDING=12
#export nwchem_hash=77ba3a6e1dd6f9ba26879d0416bb93b302f1f4f7
#export NWCHEM_TOP=/opt/nwchem
export NWCHEM_SHARE=/opt/nwchem/share/
export FFIELD=amber
export AMBER_1=$NWCHEM_SHARE/data/amber_s/
export AMBER_2=$NWCHEM_SHARE/data/amber_q/
export AMBER_3=$NWCHEM_SHARE/data/amber_x/
export AMBER_4=$NWCHEM_SHARE/data/amber_u/
export SPCE=${NWCHEM_SHARE}/data/solvents/spce.rst
export CHARMM_S=$NWCHEM_SHARE/data/charmm_s/
export CHARMM_X=$NWCHEM_SHARE/data/charmm_x/
export PATH=$PATH:/opt/nwchem/bin/
export PATH=$MPI_DIR/bin:$PATH
export NWCHEM_BASIS_LIBRARY=${NWCHEM_SHARE}//libraries/
export NWCHEM_NWPW_LIBRARY=${NWCHEM_SHARE}//libraryps/
export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:"$LD_LIBRARY_PATH" 
export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
#%runscript
#exec /bin/bash "$@"
